# bennojoy.nginx options
nginx_sites:
  - server:
      file_name: "{{ nginx_server_name }}"
      listen: 80
      server_name: "{{ nginx_server_name }}"
      location1:
        name: "/"
        proxy_pass: http://127.0.0.1:5000
        include: /etc/nginx/proxy_params
      location2:
            name: "/websocket"
            proxy_pass: http://127.0.0.1:5000/websocket
            proxy_http_version: 1.1
            proxy_set_header: "Upgrade $http_upgrade"
            proxy_set_header: 'Connection "upgrade"'
      
# angstwad.docker_ubuntu options
docker_opts: >
  --iptables=true

