nginx_sites:
  - server:
      file_name: "{{ nginx_server_name }}"
      listen: 80
      server_name: "{{ nginx_server_name }}"
      location1:
        name: "/"
        proxy_pass: http://localhost:5000
# git
git_repo: https://github.com/mfournierca/code2015.git
git_branch: master

