# https://github.com/ansible/ansible-modules-core/issues/1227
- name: workaround - install docker-py v1.1.0
  pip: name=docker-py version=1.1.0

- name: ensure docker daemon is started
  service: name=docker state=started

- name: pull docker image
  docker: 
    image: mfournierca/code2015
    state: present

- name: start docker image 
  docker:
    image: mfournierca/code2015
    state: running
    ports: 5000:5000
