---

- include: ../ansible-common/deploy-base-server.yml

- name: deploying dependancies
  hosts: webservers
  roles:
    - bennojoy.nginx
    - angstwad.docker_ubuntu
  sudo: True

- name: deploy app
  hosts: webservers
  roles:
    - nginx-proxy
    - docker-app 
  sudo: True
