---

- include: ../ansible-common/deploy-base-server.yml

- name: deploying app
  hosts: appservers
  roles:
    - bennojoy.nginx
    - ANXS.postgresql
    - postgresql-tables
    - pip-requirements
    - app

  sudo: True
