---

- name: deploying app
  hosts: webservers

  roles:
    - base-server
    - nginx
    - vhost-nginx
    - git
    - postgresql
    - postgresql-tables
    - pip-requirements
    - app

  sudo: True
